/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AuthLayout: typeof import('./components/layouts/main/AuthLayout.vue')['default']
    Footer: typeof import('./components/ui/Footer.vue')['default']
    Navigation: typeof import('./components/layouts/Navigation.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideBarLinks: typeof import('./components/layouts/SideBarLinks.vue')['default']
    Theme: typeof import('./components/ui/Theme.vue')['default']
    TopNavbar: typeof import('./components/layouts/TopNavbar.vue')['default']
  }
}
