/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    HomeLayout: typeof import('./components/layouts/main/HomeLayout.vue')['default']
    Navigation: typeof import('./components/ui/Navigation.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TopNavbar: typeof import('./components/layouts/TopNavbar.vue')['default']
  }
}
