/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AuthLayout: typeof import('./components/layouts/main/AuthLayout.vue')['default']
    HomeLayout: typeof import('./components/layouts/main/HomeLayout.vue')['default']
    Logo: typeof import('./components/ui/Logo.vue')['default']
    Navigation: typeof import('./components/layouts/main/Navigation.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideBar: typeof import('./components/layouts/main/SideBar.vue')['default']
    SideBarLinks: typeof import('./components/layouts/main/SideBarLinks.vue')['default']
    SideBarNavigation: typeof import('./components/layouts/main/SideBarNavigation.vue')['default']
    Theme: typeof import('./components/ui/Theme.vue')['default']
    TopNavbar: typeof import('./components/layouts/TopNavbar.vue')['default']
  }
}
